# Dependencies
kramdown:
  input: GFM
#markdown: redcarpet

highlighter: pygments

#:         true

# Permalinks
permalink:        pretty

# Setup
title:            HC MID
tagline: 'Devoted to the study of incompletely published primary sources'
description:      'Home page of the Holy Cross Manuscripts, Inscriptions and Documents Club'
url:
baseurl: 'http://HCMID.github.io'

author:
  name:           'Neel Smith'

paginate:         5


# Links:
links:
  - title: Hall of Fame
    url: /hof
  - title: Hosted events
    url: /hosted
  - title: MID outside Worcester
    url: /where
  - title: Tech help
    url: /tech
  - title: Twitter feed
    url: https://twitter.com/hcmid
    external: true
  - title: Administrative information
    url: /admin
     
     

